services:
  prometheus_env1:
    image: prom/prometheus:latest
    volumes:
      - prometheus_env1:/prometheus
      - ./env1/prometheus/:/etc/prometheus/
    ports:
      - "9091:9090"
    networks:
      - monitoring_network

  prometheus_env2:
    image: prom/prometheus:latest
    volumes:
      - prometheus_env2:/prometheus
      - ./env2/prometheus/:/etc/prometheus/
    ports:
      - "9092:9090"
    networks:
      - monitoring_network
  

  prometheus_monitoring:
    image: prom/prometheus:latest
    volumes:
      - prometheus_monitoring:/prometheus
      - ./monitoring/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    networks:
      - monitoring_network
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"

  grafana_monitoring:
    image: grafana/grafana:latest
    depends_on:
      - prometheus_monitoring
    ports:
      - "3000:3000"
    networks:
      - monitoring_network

volumes:
  prometheus_monitoring: {}
  prometheus_env1: {}
  prometheus_env2: {}

networks:
  monitoring_network:
    driver: bridge
