global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  # Scrape le Prometheus lui-même en dev

remote_write:
  - url: "http://prometheus_monitoring:9090/api/v1/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: '.*'
        target_label: 'environment'
        replacement: 'env2'